env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - 1.22.1
  - nightly-2017-12-02
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.1.8"; then
      cargo install cargo-prune --vers="0.1.8" --force;
    fi
  - if [ "${TRAVIS_RUST_VERSION}" = 1.22.1 ]; then
      rustfmt_vers=0.9.0;
      if ! rustfmt --version | grep -q $rustfmt_vers; then
        cargo install rustfmt --vers=$rustfmt_vers --force;
      fi
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
      clippy_vers=0.0.175;
      if ! cargo clippy --version | grep -q $clippy_vers; then
        cargo install clippy --vers=$clippy_vers --force;
      fi
    fi
script:
  - if [ "${TRAVIS_RUST_VERSION}" = 1.22.1 ]; then
        (
            set -x;
            cargo fmt -- --write-mode=diff &&
            cargo test --verbose --release
        );
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
        (
            set -x;
            cargo clippy --profile=test -- -D warnings
        )
    fi
before_cache:
  - cargo prune
