env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
  - windows
language: rust
rust:
  - 1.29.0
sudo: false
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.1.8"; then
      cargo install cargo-prune --vers="0.1.8" --force;
    fi
  - if ! rustfmt --version | grep -q "0.99.1-stable"; then
      rustup component add rustfmt-preview;
    fi
  - if ! cargo clippy --version | grep -q "0.0.212"; then
      rustup component add clippy-preview;
    fi
script:
  - set -x;
    cargo fmt -- --check &&
    cargo test --verbose --release
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then
        (
            set -x;
            printf "Clippy disabled for now -> cargo clippy --profile=test\n";
        )
    fi
before_cache:
  - cargo prune
