env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
  - windows
language: rust
rust:
  - 1.30.1
sudo: false
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.1.8"; then
      cargo install cargo-prune --vers="0.1.8" --force;
    fi
  - if ! rustfmt --version | grep -q "0.99.4-stable"; then
      rustup component add rustfmt-preview;
      if ! rustfmt --version | grep -q "0.99.4-stable"; then
        printf "Bad rustfmt version";
        exit 1;
      fi
    fi
  - if ! cargo clippy --version | grep -q "0.0.212"; then
      rustup component add clippy-preview;
      if ! cargo clippy --version | grep -q "0.0.212"; then
        printf "Bad clippy version";
        exit 1;
      fi
    fi
script:
  - set -x;
    cargo fmt -- --check &&
    cargo test --verbose --release
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then
        (
            set -x;
            cargo clippy --verbose --release &&
            cargo clippy --verbose --release --profile=test ;
        )
    fi
before_cache:
  - cargo prune
