[package]
authors = [
    "ustulation <ustulation@gmail.com>",
    "Andrew Cann <shum@canndrew.org>",
    "Povilas Balciunas <balciunas90@gmail.com>",
]
description = "A peer-to-peer NAT traversal library"
documentation = "https://docs.rs/p2p"
license = "MIT OR BSD-3-Clause"
name = "p2p"
readme = "README.md"
repository = "https://github.com/ustulation/p2p"
version = "0.5.2"

[dependencies]
bytes = "~0.4.5"
docopt = "~0.8.1"
env_logger = "~0.4.3"
future-utils = "~0.11.0"
futures = "~0.1.18"
get_if_addrs = "~0.4"
igd = "~0.6"
log = "~0.3.8"
maidsafe_utilities = "0.15.0"
maplit = "~1.0.1"
net-literals = "~0.1"
net2 = "~0.2.31"
quick-error = "~1.2"
rand = "~0.3.18"
serde = "~1.0"
serde_derive = "~1.0"
tokio-core = "~0.1.10"
tokio-io = "~0.1.3"
tokio-shared-udp-socket = "~0.5.1"
unwrap = "~1.1"
void = "~1.0"
safe_crypto = "~0.2.0"

[dev-dependencies]
serde_json = "~1.0"

[target.'cfg(target_os = "linux")'.dependencies]
netsim = { version = "~0.2.2", optional = true }

[features]
default = ["netsim"]

